#!/usr/bin/env node

const chalk = require('chalk');
const inquirer = require('inquirer');

const db = require('../database');

const roles = ['user', 'coordinator', 'admin'];

async function main() {
  const account = await inquirer.prompt([{
    type: 'input',
    name: 'user',
    message: 'Username',
  }, {
    type: 'password',
    name: 'password',
    message: 'Password',
    mask: '*',
  }, {
    type: 'password',
    name: 'password2',
    message: 'Confirm password',
    mask: '*',
  }, {
    type: 'list',
    name: 'role',
    message: 'Role',
    choices: roles,
  }]);

  if (account.password !== account.password2) {
    console.log(chalk.bold.red('ERR!'), 'Passwords don\'t match');
    process.exit(1);
  }

  console.log(chalk.bold.cyan('INFO'), 'Encrypting password...');
  const {key, salt} = await db.encryptPassword(account.password);

  console.log(chalk.bold.cyan('INFO'), 'Adding user...');
  const results = await db.query('INSERT INTO auth (username, password, salt, role) VALUES($1, $2, $3, $4) RETURNING *', [account.user, key, salt, account.role]);
  console.log(chalk.bold.cyan('INFO'), 'Results');
  console.log('RESULTS', results);
  console.log(chalk.bold.green('DONE'));
  db.end();
}

main();
