#!/usr/bin/env node

const chalk = require('chalk');
const inquirer = require('inquirer');

const db = require('../database');

async function main() {
  let account = await inquirer.prompt({
    type: 'input',
    name: 'user',
    message: 'Username',
  });
  console.log(chalk.bold.cyan('INFO'), 'Checking user exists...');
  const user = await db.findUser(account.user);
  if (!user) {
    console.log(chalk.bold.red('ERR!'), 'User not found');
    db.end();
    process.exit(1);
  }
  console.log(user);
  db.end();
  account = await inquirer.prompt({
    type: 'password',
    name: 'password',
    message: 'Password',
    mask: '*',
  });

  if (await db.checkPassword(user, account.password)) {
    console.log(chalk.bold.green('SUCCESS'));
    process.exit(0);
  } else {
    console.log(chalk.bold.red('ERR!'), 'Password doesn\'t match');
    process.exit(1);
  }
}

main();
