DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS membership_types CASCADE;
DROP TABLE IF EXISTS signup CASCADE;
DROP TABLE IF EXISTS signup_members CASCADE;
DROP TABLE IF EXISTS members_extra CASCADE;
DROP TABLE IF EXISTS members_history CASCADE;
